version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - ./djangosnippets/db/:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - ./djangosnippets:/code
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      /bin/sh -c
        'echo "Waiting for postgres..." &&
        while ! nc -z db 5432; do sleep 1; done &&
        echo "PostgreSQL started" &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000'
